# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesimTouch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesimTouch

  target 'AwesimTouch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesimTouchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesimTouch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesimTouch-tvOS

  target 'AwesimTouch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
